# Generated by Django 4.1.13 on 2024-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlmapping",
            name="favicon",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="urlmapping",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
